### PR TITLE
Ensure service gets restarted on changes

### PR DESCRIPTION
**Pull request by AAlvz**
This will fix the provisioning to production nodes and restart ghost service if there are changes.

### CODE REVIEW

**Comment by thetonymaster** [comment]
The test are failing on purpose?

**Comment by AAlvz** [comment]
@thetonymaster yup... I need to fix the tests to run under debian. Will do that on the weekend. Not sure why Travis test are showing up (we have no .travis.yaml file...)

**Comment by thetonymaster** [comment]
Go ahead and merge it then. :+1:

**Comment by AAlvz** [comment]
There. Fixed it. it was a config in the repo in the travis page... The builds won't show again until we have a proper .travis.yaml file @thetonymaster

**Comment by AAlvz** [comment]
Thanks! =)

**Pull request merged**
